### ISSUE TITLE
express degiskeni...

### ISSUE THREAD

**Issue by poorcoder** [huseyinbabal/nodeschool-restful-api#1]
Selam Huseyin,

./core/express.js icinde 

```
var express = require('express'),
    bodyParser = require('body-parser'),
    methodOverride = require('method-override'),
    expressJwt = require('express-jwt'),
    morgan = require('morgan'),
    unless = require('express-unless'),
    mongoose = require('mongoose'),
User = mongoose.model('User');
```

yukarida ki gibi degiskenler tanimliyoruz ama baktigimda express'i kullanmiyoruz... index.js de app degiskenine express'i atiyoruz ve calistiriyoruz bu kismi biraz aciklarmisin tam anlayamadim...

**Comment by huseyinbabal** [comment]
@poorcoder haklisin, normalde orda express gerekiyor ama modul un tekrardan koyulmasi fazladan olmus. Degisiklikleri yapip yolladim. Tesekkurler
